FROM node:12.16.3 as build-stage

WORKDIR /app
COPY front/package*.json /app/

RUN npm install --verbose
COPY ./front /app/

ENV REACT_APP_API_MELI_URL http://localhost/api

RUN npm run build

FROM nginx:1.17.0

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]