FROM node:12.16.3

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json ./

RUN npm install --verbose
# RUN npm install -g jest sequelize-cli ndb

COPY . .

CMD ["npm", "run", "start:dev"]